x-base-env: &x-base-env
  RELEASE: 2025+compose
  RUBY_BACKEND: http://ruby:4567
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: postgres

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8342:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - express
      - react
  react:
    build:
      context: react
      dockerfile: Dockerfile
      args:
        <<: *x-base-env
        REACT_APP_DSN:
        PUBLIC_BASE_URL:
        SENTRY_URL: "" # set to your self-hosted Sentry base URL
        SENTRY_AUTH_TOKEN: "" # set to your self-hosted Sentry auth token
        SENTRY_ORG: "" # set to your self-hosted Sentry organization
        SENTRY_PROJECT: "" # set to your self-hosted Sentry project
    init: true
  flask:
    build: flask
    environment:
      <<: *x-base-env
      FLASK_ENV: self-hosted
      FLASK_APP: src.main:application
      FLASK_APP_DSN: 
      FLASK_REDISHOST: redis
    init: true
  express:
    build: express
    environment:
      <<: *x-base-env
      PORT: 8081
      EXPRESS_ENV: self-hosted
      EXPRESS_APP_DSN: 
    init: true
  laravel:
    build: laravel
    environment:
      <<: *x-base-env
      LARVEL_ENV: self-hosted
      LARAVEL_APP_DSN: 
    init: true
  ruby:
    build: ruby
    environment:
      <<: *x-base-env
      RUBY_APP_DSN:
    init: true
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    init: true
    volumes:
      - ./postgres/data/empowerplant.sql:/docker-entrypoint-initdb.d/empowerplant.sql:ro
  redis:
    image: "redis:alpine"