x-base-env: &x-base-env
  RELEASE: 2023+compose
  RUBY_BACKEND: http://ruby:4567
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: postgres

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - express
      - react
  react:
    build: react
    environment:
      <<: *x-base-env
      REACT_APP_DSN: 
    init: true
    ports: [3000:3000]
  flask:
    build: flask
    environment:
      <<: *x-base-env
      FLASK_ENV: production
      FLASK_APP: src.main:application
      FLASK_APP_DSN: 
      FLASK_REDISHOST: redis
    init: true
    ports: [8080:8080]
  express:
    build: express
    environment:
      <<: *x-base-env
      PORT: 8081
      EXPRESS_ENV: production
      EXPRESS_APP_DSN: 
    init: true
    ports: [8081:8081]
  laravel:
    build: laravel
    environment:
      <<: *x-base-env
      LARAVEL_APP_DSN: 
    init: true
    ports: [8000:8000]
  ruby:
    build: ruby
    environment:
      <<: *x-base-env
      RUBY_APP_DSN:
    init: true
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    init: true
    ports: [5432:5432]
    volumes:
      - ./postgres/data/empowerplant.sql:/docker-entrypoint-initdb.d/empowerplant.sql:ro
  redis:
    image: "redis:alpine"